name: CDIS
channels:
  - conda-forge
  - brown-data-science # (pdf2svg)
dependencies:
  - python=3.7
  - pip
  - pandoc=2.5
  - numpy
  - scipy
  - autograd
  - matplotlib
  - black
#  - librsvg # Linux or OSX only ...
#  - predictmd-pdf2svg # Linux only ...
  - pip:
    - ics.py=0.4
    - "-e git+https://github.com/boisgera/pandoc@172f0f86fef8c972c2f0396f01e266934a67294a#egg=pandoc"
