channels:
  - conda-forge
  - brown-data-science # (pdf2svg)
dependencies:
  - python=3.7
  - pandoc=2.5
  - numpy
  - scipy
  - matplotlib
  - black
#  - librsvg # Linux or OSX only ...
#  - predictmd-pdf2svg # Linux only ...
  - pip:
    - "-e git+https://github.com/boisgera/pandoc@5077ea22aeae8cbacfb5a2387e3851d07d204ae1#egg=pandoc"
