channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandoc=2.5
  - numpy
  - scipy
  - matplotlib
  - pip:
    - "-e git+https://github.com/boisgera/pandoc@4abbb6c4040e427696786721243a45a91f7d401d#egg=pandoc"
